authors:
- Dynatrace LLC
build_ignore:
- .github
- .pre-commit-config.yaml
- .gitignore
- venv
description: Module to install and configure Dynatrace OneAgent deployment
documentation: https://docs.dynatrace.com/docs/setup-and-configuration/dynatrace-oneagent/deployment-orchestration/ansible
license_file: LICENSE
name: oneagent
namespace: dynatrace
readme: README.md
repository: https://github.com/Dynatrace/Dynatrace-OneAgent-Ansible
tags:
- dynatrace
- oneagent
- agent
- deployment
- monitoring
- infrastructure
- linux
- windows
version: 1.2.8.11-rc.4
