name: Get Ansible Versions

outputs:
  supported_ansible_versions:
    description: "List of supported Ansible versions"
    value: ${{ steps.get.outputs.supported_versions }}
  latest_ansible_version:
    description: "Latest Ansible version"
    value: ${{ steps.get.outputs.latest_version }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Get Ansible versions
      id: get
      uses: ./.github/actions/get-app-versions
      with:
        app: ansible
    - run: echo "Supported - ${{ steps.get.outputs.supported_versions }}"
