# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Build, test and upload"
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  get-ansible-versions:
    uses: ./.github/workflows/get-ansible-versions.yaml

  build-test-and-upload:
    needs: get-ansible-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible-version: ${{ fromJson(needs.get-ansible-versions.outputs.supported_ansible_versions) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set environment variables
        uses: ./.github/actions/set-environment-variables
      - name: Set up environment
        uses: ./.github/actions/set-up-build-environment
        with:
          ansible-version: ${{ matrix.ansible-version }}
      - name: Build the collection
        uses: ./.github/actions/build-collection
      - name: Run sanity tests
        uses: ./.github/actions/run-sanity-and-linter-tests
      - name: Run component tests
        uses: ./.github/actions/run-component-tests
        with:
          ansible-version: ${{ matrix.ansible-version }}
      - name: Upload the collection
        if: matrix.ansible-version == needs.get-ansible-versions.outputs.latest_ansible_version
        uses: ./.github/actions/upload-collection
