name: Commit date to master
on:
  release:
    types: [prereleased]
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: Upate version
        uses:  ./.github/actions/update-version
