name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: Upate version
        uses:  ./.github/actions/update-version
        with:
          version: ${{ github.event.inputs.version}}
          gha_token: ${{ secrets.BOT_TOKEN }}

      - name: Release on GitHub
        uses:  ./.github/actions/make-release
        with:
          version: ${{ github.event.inputs.version }}
          release_notes: ${{ github.event.inputs.release_notes }}
          gha_token: ${{ secrets.BOT_TOKEN }}
