name: Commit date to master
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true

jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: Upate version
        uses:  ./.github/actions/update-version
        with:
          version: ${{ github.event.inputs.version}}
